from tkinter import*
myw=Tk()
myw.geometry("800x900")
myw.title("WELCOME TO SBI BANK")
myw.config(bg="yellow")
lb1=Label(myw,text="username",fg="red",font=('arial',15),bg="yellow")
lb1.place(x=10,y=20)
tf1=Entry(myw)
tf1.place(x=150,y=22)
lb2=Label(myw,text="password",fg="blue",font=('arial',15),bg="yellow")
lb2.place(x=11,y=60)
tf2=Entry(myw,show="*")
tf2.place(x=150,y=65)
myw.mainloop()